# Generated by Django 2.2 on 2020-08-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycontacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='relate',
            new_name='relation',
        ),
    ]
